development:
  adapter: sqlite3
  database: db/development.sqlite3

# Additional configurations for other databases
# production:
#   adapter: mysql2
#   host: localhost
#   database: myapp_production
#   username: root
#   password: password
#
# test:
#   adapter: postgresql
#   host: localhost
#   database: myapp_test
#   username: postgres
#   password: password
